spring:
  application:
  name: TaskHub


  datasource:
    url: jdbc:postgresql://localhost:5432/TaskHub
    username: postgres
    password: 01032002ama
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # PAY ATTENTION, BE CAUTIOUS!!!
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

spring doc:
  swagger-ui:
    path:/swagger-ui.html